spring.application.name=accounts-service
server.port=8080

spring.datasource.url=jdbc:h2:mem:accounts_db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=admin
spring.datasource.password=admin

spring.h2.console.enabled=true

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

build.version=3.0

accounts.message=Bank accounts related local APIs
accounts.contactDetails.name=John Doe - Developer
accounts.contactDetails.email=john@example.com
accounts.onCallSupport=(222) 222-333,(222) 222-444
