build.version=1.0

accounts.message=Bank accounts related production APIs
accounts.contactDetails.name=Prod Support
accounts.contactDetails.email=prod@example.com
accounts.onCallSupport=(111) 222-333,(111) 222-444
