build.version=2.0

accounts.message=Bank accounts related local QA APIs
accounts.contactDetails.name=Smith Ray - QA Lead
accounts.contactDetails.email=john@example.com
accounts.onCallSupport=(222) 222-333,(222) 222-444
