server.port=9000

spring.datasource.url=jdbc:mysql://localhost:3308/cardsdb
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

build.version=3.0.0

cards.message=Bank cards related local QA APIs
cards.contactDetails.name=Ari
cards.contactDetails.email=ari@example.com
cards.onCallSupport=(359) 123-3334-45

# expose all management endpoints
management.endpoints.web.exposure.include=*
