server.port=9000

spring.datasource.url=jdbc:h2:mem:cards_db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=admin
spring.datasource.password=admin

spring.h2.console.enabled=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

build.version=3.0.0

cards.message=Bank cards related local QA APIs
cards.contactDetails.name=Ari
cards.contactDetails.email=ari@example.com
cards.onCallSupport=(359) 123-3334-45

# expose all management endpoints
management.endpoints.web.exposure.include=*
