spring.application.name=loans-service
server.port=8090

spring.h2.console.enabled=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:loans_db
spring.datasource.username=admin
spring.datasource.password=admin

build.version=3.4.8

loans.message=Bank cards related local QA APIs
loans.contactDetails.name=Ren
loans.contactDetails.email=ren@example.com
loans.onCallSupport=(359) 345-7865-54

